name: Build VectorAudio

on: [push]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install SFML dependencies
        run: |
          sudo apt-get install libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/
      - name: Bundle OSX
        run: |
          ./bundle_osx.sh
      - name: Archive build result
        uses: actions/upload-artifact@v2
        with:
          name: VectorAudio_osx
          path: build/VectorAudio_i386.dmg